services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - backend_storage:/app/media  # Base storage
      - ./backend/media:/app/media  # Local storage (takes precedence)
      - backend_static:/app/staticfiles
      - backend_data:/app/data
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_SECRET_KEY=insecure-dev-only-key
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    stdin_open: true # Required for react-scripts start
    tty: true # Required for react-scripts start

volumes:
  backend_storage:
  backend_static:
  backend_data: